[settings]
use_file_shell_for_executable_tasks = true
windows_executable_extensions = [ "sh", "ps1", "py" ]
unix_default_file_shell_args = "env"
unix_default_inline_shell_args = "sh -c -o errexit"
windows_default_file_shell_args = "env.exe"
windows_default_inline_shell_args = "sh.exe -c -o errexit"

[env]
MISE_SH_TASKS_DIR = "./mise-sh/"

[task_config]
includes = [
  "mise-tasks",
  "mise-sh/*.toml",
  "mise-sh.toml",
]

[tasks."foo"]
description = "Foo"
run = """
#!/usr/bin/env sh

set -o nounset -o errexit

env

echo Foo
"""
