# [settings]
# use_file_shell_for_executable_tasks = true
# windows_executable_extensions = [ "sh", "ps1", "py" ]
# unix_default_file_shell_args = "env"
# unix_default_inline_shell_args = "sh -c -o errexit"
# windows_default_file_shell_args = "env.exe"
# windows_default_inline_shell_args = "sh.exe -c -o errexit"

[task_config]
includes = [
  "mise-tasks",
  "mise-tasks/*.toml",
]

# [env]
# BB_VER = "FRP-5857-g3681e397f"
# _.path = "{{env.HOME}}/.cache/task-sh/busybox@{{env.BB_VER}}"
