[task_config]
includes = [
  "mise-tasks",
  "mise-tasks/*.toml",
]

[tools]
"http:busybox" = { version = "FRP-5857-g3681e397f", url = "https://frippery.org/files/busybox/busybox-w64u-FRP-5857-g3681e397f.exe", bin = "sh.exe", os = ["windows"] }

# [env]
# BB_VER = "FRP-5857-g3681e397f"
# _.path = "{{env.HOME}}/.cache/task-sh/busybox@{{env.BB_VER}}"
