[task_config]
includes = [
  "mise-tasks",
  "mise-tasks/*.toml",
]

# nushell/nushell: A new type of shell https://github.com/nushell/nushell
[tools."github:nushell/nushell"]
# Releases Â· nushell/nushell https://github.com/nushell/nushell/releases
version = "0.110.0"
